// base/nginx/Dockerfile.svelte
FROM nginx:alpine

LABEL version="0.0.2"
LABEL maintainer="AliuQ <aliuq@bilishare.com>"
LABEL description="Nginx with custom configuration, based on alpine. The root path is /app."

WORKDIR /app
COPY ./conf/default.svelte.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]

EXPOSE 80

// base/nginx/Dockerfile.vue
FROM nginx:alpine

LABEL version="0.0.1"
LABEL maintainer="AliuQ <aliuq@bilishare.com>"
LABEL description="Nginx with custom configuration, based on alpine. The root path is /app."

WORKDIR /app
COPY ./conf/default.vue.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]

EXPOSE 80
